### PR TITLE
Lightweight tags

### PR DESCRIPTION
**Pull request by arnemolland**
Adds a `tag` variable that allows the commit to be tagged with a lightweight tag.

### CODE REVIEW

**Review by s0 — CHANGES_REQUESTED** [review]
This looks great, nice feature.

Could i ask you to add some unit tests to this too please?

(it looks like the actions won't work in your fork, so i'll need to check coverage locally after you've added the tests).

**Comment by arnemolland** [comment]
Sure, I'll find the time!

**Comment by s0** [comment]
Hi @arnemolland!

I'd like to get this in so i'll work adding the unit tests.

**Comment by s0** [comment]
To allow me to check that CI tests run as expected for this, i'll merge this into a feature branch and then open a new PR for that! :)

**Comment by s0** [comment]
This feature is now included as part of the [v2.4.0](https://github.com/s0/git-publish-subdir-action/releases/tag/v2.4.0) release, thanks again for this!

**Comment by arnemolland** [comment]
Great, thanks @s0!

**Pull request merged**
